// Profile page module (single clean implementation with 2FA method selection)
const api = { list: '/profile/photos', upload: '/profile/photos', set: id => `/profile/photos/${id}/set-profile`, delete: id => `/profile/photos/${id}`, presence: '/profile/presence', heartbeat: '/profile/heartbeat' };
let _pollInterval = null, _hbInterval = null;
const POLL_PERIOD = 5000;
let _visibilityHandler = null, _beforeUnloadHandler = null;
let _btnChangePhotoHandler = null, _inputPhotoHandler = null;
let _avatarClickHandler = null, _galleryClickHandler = null;
let _reopen2faSubmitHandler = null, _reopen2faCancelHandler = null;
let _resetPasswordMenuHandler = null, _toggle2faHandler = null;

async function refreshGallery(){
	try {
		const r=await axios.get(api.list); const photos=r.data?.photos||[]; const container=$('#photo-gallery'); if(!container) return; container.empty();
		if(!photos.length){ container.append('<p class="text-muted">No hay fotos en la galería.</p>'); return; }
		photos.forEach(p=>{ const origin=location.origin; const metaDefault=(document.querySelector('meta[name="default-avatar"]')||{}).content; const defaultAvatar=window.__defaultAvatar||metaDefault||(origin+'/images/default-avatar.png'); const src=p.url||p.secure_url||(p.path?origin+'/storage/'+p.path.replace(/^\/+/, ''):defaultAvatar); container.append(`<div class="position-relative m-1" style="width:120px"><img src="${src}" alt="${p.caption||''}" width="120" height="120" class="rounded object-fit-cover gallery-photo" data-photo-id="${p.id}"><div class="position-absolute top-0 end-0 m-1 d-flex flex-column gap-1"><button type="button" class="btn btn-sm btn-light gallery-preview-btn" title="Ver" data-photo-id="${p.id}"><i class="bi bi-arrows-fullscreen"></i></button><button type="button" class="btn btn-sm btn-success gallery-set-btn" title="Usar como perfil" data-photo-id="${p.id}"><i class="bi bi-person-circle"></i></button><button type="button" class="btn btn-sm btn-danger gallery-delete-btn" title="Eliminar" data-photo-id="${p.id}"><i class="bi bi-trash"></i></button></div></div>`); });
		let profilePhoto=photos.find(pp=>pp.is_profile||pp.is_profile===1)||photos[0];
		if(profilePhoto){ const origin=location.origin; const profSrc=profilePhoto.url||profilePhoto.secure_url||(profilePhoto.path?origin+'/storage/'+profilePhoto.path.replace(/^\/+/, ''):null); if(profSrc){ const busted=profSrc+'?_=' + Date.now(); document.querySelectorAll('#profile-avatar-img, #nav-avatar-img, .profile-avatar-img, img[data-profile-photo]').forEach(img=>{ try{ img.src=busted; }catch(_){} }); try{ window.dispatchEvent(new CustomEvent('profile-photo-changed',{detail:{src:busted}})); }catch(_){} } }
	}catch(e){ modalNotification?.('Error','No se pudo cargar la galería',{template:'danger'},true,{xhr:e?.response}); }
}

async function fetchStatus(){ try{ const r=await axios.get('/profile/status'); if(r.data?.ok){ const status=r.data.status||'offline'; const labels={online:'Online',busy:'Ocupado',dnd:'No molestar',away:'Ausente',offline:'No disponible'}; const elDesc=document.getElementById('profile-presence-desc'); if(elDesc) elDesc.textContent=labels[status]||status; const colors={online:'#28a745',busy:'#fd7e14',dnd:'#dc3545',away:'#ffc107',offline:'#6c757d'}; const el=document.getElementById('profile-presence'); if(el) el.style.background=colors[status]||colors.offline; }}catch(_){} }
function startPolling(){ if(_pollInterval) return; fetchStatus(); _pollInterval=setInterval(fetchStatus,POLL_PERIOD); }
function stopPolling(){ if(_pollInterval){ clearInterval(_pollInterval); _pollInterval=null; } }
async function sendHeartbeat(){ try{ await axios.post(api.heartbeat); }catch(_){} }
function startHeartbeat(){ if(_hbInterval) return; sendHeartbeat(); _hbInterval=setInterval(sendHeartbeat,30000); }
function stopHeartbeat(){ if(_hbInterval){ clearInterval(_hbInterval); _hbInterval=null; } }

export function init(){
	// Foto: subida
	const btn=document.getElementById('btn-change-photo'); const input=document.getElementById('input-photo');
	if(btn&&input){ _btnChangePhotoHandler=()=>input.click(); btn.addEventListener('click',_btnChangePhotoHandler); _inputPhotoHandler=async function(){ const f=this.files[0]; if(!f) return; const fd=new FormData(); fd.append('photo',f); try{ const r=await axios.post(api.upload,fd); if(r.data?.ok){ await refreshGallery(); modalNotification?.('Foto subida','Foto subida correctamente',{template:'success'});} else modalNotification?.('Error','No se pudo subir la foto',{template:'danger'}); }catch(err){ modalNotification?.('Error','No se pudo subir la foto',{template:'danger'},true,{xhr:err?.response}); } finally { try{ this.value=''; }catch(_){} } }; input.addEventListener('change',_inputPhotoHandler); }
	// Presencia & heartbeat
	startPolling(); if(document.visibilityState==='visible') startHeartbeat(); _visibilityHandler=()=>{ if(document.visibilityState==='visible') startHeartbeat(); else stopHeartbeat(); }; document.addEventListener('visibilitychange',_visibilityHandler); _beforeUnloadHandler=()=>{ navigator.sendBeacon && navigator.sendBeacon(api.heartbeat); }; window.addEventListener('beforeunload',_beforeUnloadHandler);
	// Modal vista previa
	if(!document.getElementById('profileImagePreviewModal')) document.body.insertAdjacentHTML('beforeend','<div class="modal fade" id="profileImagePreviewModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered modal-lg"><div class="modal-content"><div class="modal-body text-center p-0"><img id="profileImagePreviewModalImg" src="" style="width:100%;height:auto" alt="preview"></div></div></div></div>');
	// Modal reapertura 2FA
	(function(){ let m=document.getElementById('reopen2faModal'); if(!m){ document.body.insertAdjacentHTML('beforeend','<div class="modal fade" id="reopen2faModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Confirmar reapertura de sesión</h5></div><div class="modal-body"><p>Introduce el código de 6 dígitos enviado.</p><input id="reopen2faCode" class="form-control mb-2" maxlength="6" inputmode="numeric" placeholder="Código"><div id="reopen2faError" class="text-danger small" style="display:none"></div></div><div class="modal-footer"><button id="reopen2faCancel" type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button id="reopen2faSubmit" type="button" class="btn btn-primary">Confirmar</button></div></div></div></div>'); m=document.getElementById('reopen2faModal'); }
		const inp=m.querySelector('#reopen2faCode'); const err=m.querySelector('#reopen2faError'); const sub=m.querySelector('#reopen2faSubmit'); const can=m.querySelector('#reopen2faCancel');
		_reopen2faSubmitHandler=async()=>{ err.style.display='none'; const code=inp.value.trim(); if(!/^[0-9]{6}$/.test(code)){ err.textContent='Código inválido'; err.style.display='block'; return; } sub.disabled=true; try{ const r=await fetch('/profile/heartbeat/confirm',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content},body:JSON.stringify({code})}); const j=await r.json(); if(j.ok){ (bootstrap.Modal.getInstance(m)||new bootstrap.Modal(m)).hide(); location.reload(); } else { err.textContent=j.message||'Código incorrecto'; err.style.display='block'; } }catch(_){ err.textContent='Error de red'; err.style.display='block'; } finally { sub.disabled=false; } };
		sub.addEventListener('click',_reopen2faSubmitHandler); _reopen2faCancelHandler=()=>{ err.style.display='none'; inp.value=''; }; can.addEventListener('click',_reopen2faCancelHandler); window.showReopen2faModal=()=>{ err.style.display='none'; inp.value=''; (bootstrap.Modal.getInstance(m)||new bootstrap.Modal(m)).show(); setTimeout(()=>inp.focus(),250); };
	})();
	// Item reset password
	const itemReset=document.getElementById('profileResetPasswordItem'); if(itemReset){ _resetPasswordMenuHandler=e=>{ if(e) e.preventDefault(); modalConfirm({ title:'Cambiar contraseña', body:'<p>Se enviará un enlace a tu correo. ¿Continuar?</p>', confirmLabel:'Enviar', cancelLabel:'Cancelar', onClickYes: async()=>{ try{ const r=await axios.post('/profile/password/reset-email'); if(r.data?.ok) modalConfirm({title:'Enviado', body:'<p>Revisa tu correo.</p>', btnsType:'ac'},'normal'); else modalConfirm({title:'Error', body:`<p>${r.data?.message||'No se pudo enviar.'}</p>`, btnsType:'ac'},'normal'); }catch(err){ let msg='No se pudo enviar.'; const rs=err.response; if(rs){ if(rs.status===429) msg='Demasiadas solicitudes.'; else if(rs.status===419) msg='Sesión expirada.'; else if(rs.data?.message) msg=rs.data.message; } modalConfirm({title:'Error', body:`<p>${msg}</p>`, btnsType:'ac'},'normal'); } }} ,'normal'); }; itemReset.addEventListener('click',_resetPasswordMenuHandler); }
	// Toggle 2FA con selección método
	const item2fa=document.getElementById('profileToggle2faItem'); if(item2fa){ _toggle2faHandler=async e=>{ if(e) e.preventDefault(); const current=item2fa.dataset.twoFactorEnabled==='1'; if(current){ item2fa.classList.add('disabled'); try{ const r=await axios.post('/profile/2fa/toggle'); if(r.data?.ok){ item2fa.dataset.twoFactorEnabled='0'; item2fa.textContent='Activar 2FA'; modalNotification?.('2FA','2FA desactivado',{template:'success'});} else modalNotification?.('Error','No se pudo desactivar',{template:'danger'}); }catch(_){ modalNotification?.('Error','Error de red',{template:'danger'});} finally { item2fa.classList.remove('disabled'); } return; }
		let m=document.getElementById('twoFactorEnableModal'); if(!m){ document.body.insertAdjacentHTML('beforeend','<div class="modal fade" id="twoFactorEnableModal" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Activar 2FA</h5></div><div class="modal-body"><p>Selecciona cómo recibir el código.</p><div class="mb-2"><div class="form-check"><input class="form-check-input" type="radio" name="twofa_method" id="twofa_method_email" value="email" checked><label class="form-check-label" for="twofa_method_email">Email</label></div><div class="form-check"><input class="form-check-input" type="radio" name="twofa_method" id="twofa_method_phone" value="phone"><label class="form-check-label" for="twofa_method_phone">Teléfono (SMS)</label></div></div><div id="twofaPhoneWrap" class="mb-3" style="display:none"><label class="form-label" for="twofa_phone_input">Teléfono</label><input id="twofa_phone_input" class="form-control" maxlength="25" placeholder="Ej: +1 809 555 1234"><div id="twofa_phone_error" class="text-danger small" style="display:none"></div></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button><button id="twofa_enable_btn" type="button" class="btn btn-primary">Activar</button></div></div></div></div>'); m=document.getElementById('twoFactorEnableModal'); const radios=m.querySelectorAll('input[name="twofa_method"]'); const phoneWrap=m.querySelector('#twofaPhoneWrap'); const phoneInput=m.querySelector('#twofa_phone_input'); const phoneErr=m.querySelector('#twofa_phone_error'); radios.forEach(r=>r.addEventListener('change',()=>{ const v=m.querySelector('input[name="twofa_method"]:checked')?.value; phoneWrap.style.display=v==='phone'?'':'none'; })); m.querySelector('#twofa_enable_btn').addEventListener('click', async()=>{ phoneErr.style.display='none'; const method=m.querySelector('input[name="twofa_method"]:checked')?.value||'email'; let phoneVal=''; if(method==='phone'){ phoneVal=(phoneInput.value||'').trim(); if(!phoneVal){ phoneErr.textContent='Ingresa teléfono'; phoneErr.style.display='block'; return; } }
			const btn=m.querySelector('#twofa_enable_btn'); btn.disabled=true; try{ if(method==='phone'&&phoneVal){ await axios.post('/profile/phone',{phone:phoneVal}); }
				const r=await axios.post('/profile/2fa/toggle',{method}); if(r.data?.ok && r.data.enabled){ item2fa.dataset.twoFactorEnabled='1'; item2fa.textContent='Desactivar 2FA'; modalNotification?.('2FA','2FA activado ('+(method==='phone'?'teléfono':'email')+')',{template:'success'}); (bootstrap.Modal.getInstance(m)||new bootstrap.Modal(m)).hide(); } else if(r.data?.phone_required){ phoneErr.textContent=r.data.message||'Se requiere teléfono'; phoneErr.style.display='block'; } else { modalNotification?.('Error','No se pudo activar 2FA',{template:'danger'}); } }catch(errAct){ modalNotification?.('Error', errAct?.response?.data?.message || 'Error de red',{template:'danger'}); } finally { btn.disabled=false; }
		}); }
		(bootstrap.Modal.getInstance(m)||new bootstrap.Modal(m)).show();
	}; item2fa.addEventListener('click',_toggle2faHandler); }
	// Avatar preview
	const avatar=document.getElementById('profile-avatar'); const modalImg=document.getElementById('profileImagePreviewModalImg'); _avatarClickHandler=()=>{ const src=document.getElementById('profile-avatar-img')?.src; if(!src) return; modalImg.src=src; (bootstrap.Modal.getInstance(document.getElementById('profileImagePreviewModal'))||new bootstrap.Modal(document.getElementById('profileImagePreviewModal'))).show(); }; if(avatar) avatar.addEventListener('click',_avatarClickHandler);
	// Interacciones galería
	_galleryClickHandler=e=>{ const t=e.target; const btn=t.closest?.('.gallery-preview-btn, .gallery-set-btn, .gallery-delete-btn'); const modalEl=document.getElementById('profileImagePreviewModal'); const modalImg=document.getElementById('profileImagePreviewModalImg'); if(!btn){ const img=t.closest?.('.gallery-photo'); if(img){ modalImg.src=img.src; (bootstrap.Modal.getInstance(modalEl)||new bootstrap.Modal(modalEl)).show(); } return; } const pid=btn.dataset.photoId; if(!pid) return; if(btn.classList.contains('gallery-preview-btn')){ const img=document.querySelector(`[data-photo-id="${pid}"]`); if(img){ modalImg.src=img.src; (bootstrap.Modal.getInstance(modalEl)||new bootstrap.Modal(modalEl)).show(); } return; } if(btn.classList.contains('gallery-set-btn')){ (async()=>{ try{ const r=await axios.post(api.set(pid)); if(r.data?.ok){ modalNotification?.('Foto perfil','Actualizada',{template:'success'}); await refreshGallery(); } else modalNotification?.('Error','No se pudo establecer',{template:'danger'}); }catch(e2){ modalNotification?.('Error','No se pudo establecer',{template:'danger'},true,{xhr:e2?.response}); } })(); return; } if(btn.classList.contains('gallery-delete-btn')){ const doDelete=async()=>{ try{ const r=await axios.delete(api.delete(pid)); if(r.data?.ok){ modalNotification?.('Foto eliminada','Eliminada correctamente',{template:'success'}); await refreshGallery(); } else modalNotification?.('Error','No se pudo eliminar',{template:'danger'}); }catch(e2){ modalNotification?.('Error','No se pudo eliminar',{template:'danger'},true,{xhr:e2?.response}); } }; modalConfirm({ title:'Eliminar foto', body:'<p>¿Eliminar esta foto?</p>', buttons:[{text:'Cancelar', className:'btn-outline-secondary', dismiss:true},{text:'Eliminar', className:'btn-danger', onClick:()=>doDelete()}] },'normal'); } };
	const gallery=document.getElementById('photo-gallery'); if(gallery) gallery.addEventListener('click',_galleryClickHandler);
	refreshGallery();
}

export function destroy(){
	stopPolling(); stopHeartbeat();
	try{ if(_btnChangePhotoHandler) document.getElementById('btn-change-photo')?.removeEventListener('click',_btnChangePhotoHandler);}catch(_){}
	try{ if(_inputPhotoHandler) document.getElementById('input-photo')?.removeEventListener('change',_inputPhotoHandler);}catch(_){}
	try{ if(_avatarClickHandler) document.getElementById('profile-avatar')?.removeEventListener('click',_avatarClickHandler);}catch(_){}
	try{ if(_galleryClickHandler) document.getElementById('photo-gallery')?.removeEventListener('click',_galleryClickHandler);}catch(_){}
	try{ if(_reopen2faSubmitHandler) document.getElementById('reopen2faSubmit')?.removeEventListener('click',_reopen2faSubmitHandler);}catch(_){}
	try{ if(_reopen2faCancelHandler) document.getElementById('reopen2faCancel')?.removeEventListener('click',_reopen2faCancelHandler);}catch(_){}
	try{ if(_resetPasswordMenuHandler) document.getElementById('profileResetPasswordItem')?.removeEventListener('click',_resetPasswordMenuHandler);}catch(_){}
	try{ if(_toggle2faHandler) document.getElementById('profileToggle2faItem')?.removeEventListener('click',_toggle2faHandler);}catch(_){}
	try{ if(_visibilityHandler) document.removeEventListener('visibilitychange',_visibilityHandler);}catch(_){}
	try{ if(_beforeUnloadHandler) window.removeEventListener('beforeunload',_beforeUnloadHandler);}catch(_){}
	_btnChangePhotoHandler=_inputPhotoHandler=_avatarClickHandler=_galleryClickHandler=_visibilityHandler=_beforeUnloadHandler=_reopen2faSubmitHandler=_reopen2faCancelHandler=_resetPasswordMenuHandler=_toggle2faHandler=null;
}